export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#171933',
  SECONDARY_BACKGROUND_COLOR: '#1e2144',
  TERTIARY_BACKGROUND_COLOR: '#0a0c29',
  PRIMARY_TEXT_COLOR: '#eee',
  SECONDARY_TEXT_COLOR: '#ccc',
  PRIMARY_BORDER_COLOR: '#aaa',
};

export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#D3CEC8',
  SECONDARY_BACKGROUND_COLOR: '#E5DFD9',
  TERTIARY_BACKGROUND_COLOR: '#C1BFBC',
  PRIMARY_TEXT_COLOR: '#222',
  SECONDARY_TEXT_COLOR: '#333',
  PRIMARY_BORDER_COLOR: '#555',
};
